-- ============================================
-- HIGHSCORES TABLE (for Survival Mode)
-- ============================================

-- Create highscores table
create table if not exists highscores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  score int not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table highscores enable row level security;

-- Policies
-- Everyone can see highscores
create policy "Highscores are viewable by everyone"
  on highscores for select
  using (true);

-- Users can insert their own highscores
create policy "Users can insert their own highscores"
  on highscores for insert
  with check (auth.uid() = user_id);

-- Optional: Index for faster ordering
create index if not exists highscores_score_idx on highscores(score desc);
