-- Copy this SQL into the Supabase SQL Editor

-- 1. Create table to store flag statistics
create table flag_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  country_code text not null,
  times_correct int default 0,
  times_wrong int default 0,
  last_played_at timestamp with time zone default timezone('utc'::text, now()),
  
  -- Prevent duplicates: one row per user per country
  unique(user_id, country_code)
);

-- 2. Enable Row Level Security (RLS)
alter table flag_stats enable row level security;

-- 3. Create policies to allow users to manage ONLY their own data
create policy "Users can select their own stats"
  on flag_stats for select
  using (auth.uid() = user_id);

create policy "Users can insert their own stats"
  on flag_stats for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own stats"
  on flag_stats for update
  using (auth.uid() = user_id);

-- ============================================
-- PROFILES TABLE (for usernames)
-- ============================================

-- 4. Create profiles table to store usernames
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Enable Row Level Security
alter table profiles enable row level security;

-- 6. Create policies for profiles
create policy "Profiles are viewable by everyone"
  on profiles for select
  using (true);

create policy "Users can insert their own profile"
  on profiles for insert
  with check (auth.uid() = id);

create policy "Users can update their own profile"
  on profiles for update
  using (auth.uid() = id);

-- 7. Automated Trigger for profile creation (BEST PRACTICE)
-- This ensures a profile is created EVEN IF the client-side insert fails (e.g. before email confirmation)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id, 
    coalesce(
      (new.raw_user_meta_data->>'username'), 
      split_part(new.email, '@', 1) || '_' || (floor(random() * 888) + 111)::text
    )
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger should run after every auth user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
