// Mapping von englischen zu deutschen Ländernamen
export const countryNameMap: Record<string, string> = {
	"Afghanistan": "Afghanistan",
	"Albania": "Albanien",
	"Algeria": "Algerien",
	"Andorra": "Andorra",
	"Angola": "Angola",
	"Antigua and Barbuda": "Antigua und Barbuda",
	"Argentina": "Argentinien",
	"Armenia": "Armenien",
	"Australia": "Australien",
	"Austria": "Österreich",
	"Azerbaijan": "Aserbaidschan",
	"Bahamas": "Bahamas",
	"Bahrain": "Bahrain",
	"Bangladesh": "Bangladesch",
	"Barbados": "Barbados",
	"Belarus": "Weißrussland",
	"Belgium": "Belgien",
	"Belize": "Belize",
	"Benin": "Benin",
	"Bhutan": "Bhutan",
	"Bolivia": "Bolivien",
	"Bosnia and Herzegovina": "Bosnien und Herzegowina",
	"Botswana": "Botswana",
	"Brazil": "Brasilien",
	"Brunei": "Brunei",
	"Bulgaria": "Bulgarien",
	"Burkina Faso": "Burkina Faso",
	"Burundi": "Burundi",
	"Cabo Verde": "Kap Verde",
	"Cambodia": "Kambodscha",
	"Cameroon": "Kamerun",
	"Canada": "Kanada",
	"Caribbean Netherlands": "Karibische Niederlande",
	"Cayman Islands": "Kaimaninseln",
	"Christmas Island": "Weihnachtsinsel",
	"Cocos (Keeling) Islands": "Kokosinseln",
	"Cook Islands": "Cookinseln",
	"Curaçao": "Curaçao",
	"Central African Republic": "Zentralafrikanische Republik",
	"Chad": "Tschad",
	"Chile": "Chile",
	"China": "China",
	"Colombia": "Kolumbien",
	"Comoros": "Komoren",
	"Congo": "Kongo",
	"Costa Rica": "Costa Rica",
	"Croatia": "Kroatien",
	"Cuba": "Kuba",
	"Côte d'Ivoire": "Elfenbeinküste",
	"Cyprus": "Zypern",
	"Czechia": "Tschechien",
	"Denmark": "Dänemark",
	"Djibouti": "Dschibuti",
	"Dominica": "Dominica",
	"Dominican Republic": "Dominikanische Republik",
	"DR Congo": "Demokratische Republik Kongo",
	"Ecuador": "Ecuador",
	"Egypt": "Ägypten",
	"El Salvador": "El Salvador",
	"Equatorial Guinea": "Äquatorialguinea",
	"Eritrea": "Eritrea",
	"Estonia": "Estland",
	"Eswatini": "Eswatini",
	"Ethiopia": "Äthiopien",
	"Fiji": "Fidschi",
	"Finland": "Finnland",
	"France": "Frankreich",
	"French Guiana": "Französisch-Guyana",
	"French Guyana": "Französisch-Guyana",
	"French Polynesia": "Französisch-Polynesien",
	"French Southern and Antarctic Lands": "Französische Süd- und Antarktisgebiete",
	"Gabon": "Gabun",
	"Gambia": "Gambia",
	"Georgia": "Georgien",
	"Germany": "Deutschland",
	"Ghana": "Ghana",
	"Greece": "Griechenland",
	"Grenada": "Grenada",
	"Guatemala": "Guatemala",
	"Guinea": "Guinea",
	"Guinea-Bissau": "Guinea-Bissau",
	"Guyana": "Guyana",
	"Haiti": "Haiti",
	"Honduras": "Honduras",
	"Hungary": "Ungarn",
	"Iceland": "Island",
	"India": "Indien",
	"Indonesia": "Indonesien",
	"Iran": "Iran",
	"Iraq": "Irak",
	"Ireland": "Irland",
	"Israel": "Israel",
	"Italy": "Italien",
	"Jamaica": "Jamaika",
	"Jersey": "Jersey",
	"Japan": "Japan",
	"Jordan": "Jordanien",
	"Kazakhstan": "Kasachstan",
	"Kenya": "Kenia",
	"Kiribati": "Kiribati",
	"Kosovo": "Kosovo",
	"Kuwait": "Kuwait",
	"Kyrgyzstan": "Kirgisistan",
	"Laos": "Laos",
	"Latvia": "Lettland",
	"Lebanon": "Libanon",
	"Lesotho": "Lesotho",
	"Liberia": "Liberia",
	"Libya": "Libyen",
	"Liechtenstein": "Liechtenstein",
	"Lithuania": "Litauen",
	"Luxembourg": "Luxemburg",
	"Madagascar": "Madagaskar",
	"Malawi": "Malawi",
	"Malaysia": "Malaysia",
	"Maldives": "Malediven",
	"Mali": "Mali",
	"Malta": "Malta",
	"Marshall Islands": "Marshallinseln",
	"Mauritania": "Mauretanien",
	"Mauritius": "Mauritius",
	"Mexico": "Mexiko",
	"Micronesia": "Mikronesien",
	"Moldova": "Moldau",
	"Monaco": "Monaco",
	"Montserrat": "Montserrat",
	"Mongolia": "Mongolei",
	"Montenegro": "Montenegro",
	"Morocco": "Marokko",
	"Mozambique": "Mosambik",
	"Myanmar": "Myanmar",
	"Namibia": "Namibia",
	"Nauru": "Nauru",
	"Nepal": "Nepal",
	"Netherlands": "Niederlande",
	"New Caledonia": "Neukaledonien",
	"Niue": "Niue",
	"Norfolk Island": "Norfolkinsel",
	"New Zealand": "Neuseeland",
	"Nicaragua": "Nicaragua",
	"Niger": "Niger",
	"Nigeria": "Nigeria",
	"North Korea": "Nordkorea",
	"North Macedonia": "Nordmazedonien",
	"Norway": "Norwegen",
	"Oman": "Oman",
	"Pakistan": "Pakistan",
	"Palau": "Palau",
	"Palestine": "Palästina",
	"Panama": "Panama",
	"Pitcairn Islands": "Pitcairninseln",
	"Puerto Rico": "Puerto Rico",
	"Papua New Guinea": "Papua-Neuguinea",
	"Paraguay": "Paraguay",
	"Peru": "Peru",
	"Philippines": "Philippinen",
	"Poland": "Polen",
	"Portugal": "Portugal",
	"Qatar": "Katar",
	"Romania": "Rumänien",
	"Russia": "Russland",
	"Réunion": "Réunion",
	"Rwanda": "Ruanda",
	"Saint Kitts and Nevis": "St. Kitts und Nevis",
	"Saint Lucia": "St. Lucia",
	"Saint Vincent and the Grenadines": "St. Vincent und die Grenadinen",
	"Samoa": "Samoa",
	"San Marino": "San Marino",
	"São Tomé and Príncipe": "São Tomé und Príncipe",
	"Saudi Arabia": "Saudi-Arabien",
	"Sint Maarten": "Sint Maarten",
	"South Georgia and the South Sandwich Islands": "Südgeorgien und die Südlichen Sandwichinseln",
	"Saint Helena, Ascension and Tristan da Cunha": "St. Helena, Ascension und Tristan da Cunha",
	"Saint Pierre and Miquelon": "Saint-Pierre und Miquelon",
	"Senegal": "Senegal",
	"Serbia": "Serbien",
	"Seychelles": "Seychellen",
	"Sierra Leone": "Sierra Leone",
	"Singapore": "Singapur",
	"Slovakia": "Slowakei",
	"Slovenia": "Slowenien",
	"Solomon Islands": "Salomonen",
	"Somalia": "Somalia",
	"South Africa": "Südafrika",
	"South Korea": "Südkorea",
	"South Sudan": "Südsudan",
	"Spain": "Spanien",
	"Sri Lanka": "Sri Lanka",
	"Sudan": "Sudan",
	"Suriname": "Suriname",
	"Sweden": "Schweden",
	"Switzerland": "Schweiz",
	"Syria": "Syrien",
	"Taiwan": "Taiwan",
	"Tajikistan": "Tadschikistan",
	"Tanzania": "Tansania",
	"Thailand": "Thailand",
	"Tokelau": "Tokelau",
	"Turks and Caicos Islands": "Turks- und Caicosinseln",
	"Timor-Leste": "Osttimor",
	"Togo": "Togo",
	"Tonga": "Tonga",
	"Trinidad and Tobago": "Trinidad und Tobago",
	"Tunisia": "Tunesien",
	"Turkey": "Türkei",
	"Turkmenistan": "Turkmenistan",
	"Tuvalu": "Tuvalu",
	"Uganda": "Uganda",
	"Ukraine": "Ukraine",
	"United Arab Emirates": "Vereinigte Arabische Emirate",
	"United Kingdom": "Vereinigtes Königreich",
	"United States": "Vereinigte Staaten",
	"Uruguay": "Uruguay",
	"Uzbekistan": "Usbekistan",
	"Vanuatu": "Vanuatu",
	"Vatican City": "Vatikanstadt",
	"Venezuela": "Venezuela",
	"Vietnam": "Vietnam",
	"Virgin Islands (British)": "Britische Jungferninseln",
	"Virgin Islands (U.S.)": "Amerikanische Jungferninseln",
	"Wallis and Futuna": "Wallis und Futuna",
	"Western Sahara": "Westsahara",
	"Yemen": "Jemen",
	"Zambia": "Sambia",
	"Zimbabwe": "Simbabwe",

	// Fehlende Länder/Territorien hinzufügen:
	"Åland Islands": "Åland",
	"American Samoa": "Amerikanisch-Samoa",
	"Anguilla": "Anguilla",
	"Aruba": "Aruba",
	"Bermuda": "Bermuda",
	"Bonaire": "Bonaire",
	"Bouvet Island": "Bouvetinsel",
	"British Indian Ocean Territory": "Britisches Territorium im Indischen Ozean",
	"Falkland Islands": "Falklandinseln",
	"Faroe Islands": "Färöer",
	"Gibraltar": "Gibraltar",
	"Greenland": "Grönland",
	"Guadeloupe": "Guadeloupe",
	"Guam": "Guam",
	"Guernsey": "Guernsey",
	"Hong Kong": "Hongkong",
	"Isle of Man": "Isle of Man",
	"Macao": "Macau",
	"Martinique": "Martinique",
	"Mayotte": "Mayotte",
	"Northern Mariana Islands": "Nördliche Marianen",
	"Saint Barthélemy": "Saint-Barthélemy",
	"Saint Martin": "Saint-Martin",
	"Svalbard and Jan Mayen": "Svalbard und Jan Mayen",
	"United States Minor Outlying Islands": "Amerikanische Außengebiete im Pazifik", // Bereits vorhanden
	// Updated/Added mappings to match API common names
	"British Virgin Islands": "Britische Jungferninseln",
	"Cape Verde": "Kap Verde",
	"Heard Island and McDonald Islands": "Heard und McDonaldinseln",
	"Ivory Coast": "Elfenbeinküste",
	"Republic of the Congo": "Republik Kongo",
	"South Georgia": "Südgeorgien und die Südlichen Sandwichinseln",
	"United States Virgin Islands": "Amerikanische Jungferninseln",
};

// Hilfsfunktion zum Abrufen des deutschen Namens
export function getGermanName(englishName: string): string {
	return countryNameMap[englishName] || englishName;
}

